### ISSUE TITLE
Index out of bound errors

### ISSUE THREAD

**Issue by datadanb** [CyberTimon/Powerpointer-For-Local-LLMs#2]
Hi there,

First off, thank you for creating this...the potential I can see of it where I work is incredible!

However, I am seeing the same error frequently:   File "/home/ec2-user/SageMaker/.cs/conda/envs/textgen/lib/python3.10/site-packages/transformers/models/gptj/modeling_gptj.py", line 223, in forward
    sincos = torch.gather(embed_positions, 1, repeated_position_ids)
RuntimeError: index 2048 is out of bounds for dimension 1 with size 2048

I am running this on AWS Sagemaker on a CPU backed instance (yet to try on a GPU, but will later on) and following your example with AI as the topic I am always greeted with this error. Any ideas?! I am able to run the textegeneration API running ok (I think): 

(textgen) [ec2-user@ip-10-10-1-139 text-generation-webui]$ python server.py --api --model eleutherai_gpt-j-6b --model-dir ../text-generation-webui/models/ --verbose --cpu --load-in-8bit
/home/ec2-user/SageMaker/.cs/conda/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
INFO:Loading eleutherai_gpt-j-6b...
INFO:Loaded the model in 25.50 seconds.

Help?
Cheers,
Dan

**Comment by datadanb** [comment]
Great, thanks @CyberTimon! Thanks for such a speedy response! Will take your advice and give it a shot :)

**Comment by datadanb** [comment]
So I downloaded a LLaMA model from HF and the first try it's worked a treat, thanks again @CyberTimon. Issue fixed.

**Comment by CyberTimon** [comment]
Nice to hear! Have fun and feel free to open another issue if things don't work how they should.
